# LOADING THE MODEL and preproceesing

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("laptop_data.csv")

In [3]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Cpu               1303 non-null   object
 6   Ram               1303 non-null   object
 7   Memory            1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price             1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [5]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1303.0,651.000000,376.288010,0.00,325.50,651.00,976.5000,1302.00
Inches,1303.0,15.017191,1.426304,10.10,14.00,15.60,15.6000,18.40
Price,1303.0,59870.042910,37243.201786,9270.72,31914.72,52054.56,79274.2464,324954.72

In [6]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [7]:
df = df.drop(columns=['Unnamed: 0'],axis=1)

In [8]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [9]:
df.nunique()

Company              19
TypeName              6
Inches               18
ScreenResolution     40
Cpu                 118
Ram                   9
Memory               39
Gpu                 110
OpSys                 9
Weight              179
Price               791
dtype: int64

In [10]:
df["Ram"] = df["Ram"].str.replace("GB", "").astype(int)

In [11]:
df["Weight"] = df["Weight"].str.replace("kg", "").astype(float)

In [12]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080

In [13]:
df["ScreenWidth"] = df["ScreenResolution"].str.extract(r"(\d+)x\d+").astype(int)

df["ScreenHeight"] = df["ScreenResolution"].str.extract(r"\d+x(\d+)").astype(int)

df["IPS"] = df["ScreenResolution"].str.contains("IPS", case=False).astype(int)

In [17]:
df[["ScreenWidth", "ScreenHeight", "IPS"]].head()

   ScreenWidth  ScreenHeight  IPS
0         2560          1600    1
1         1440           900    0
2         1920          1080    0
3         2880          1800    1
4         2560          1600    1

In [18]:
df.drop("ScreenResolution", axis=1, inplace=True)

In [19]:
df["CpuBrand"] = df["Cpu"].str.split().str[0]

df["CpuSpeed"] = df["Cpu"].str.extract(r"(\d+\.?\d*)GHz").astype(float)

In [20]:
df.drop("Cpu", axis=1, inplace=True)

In [22]:
df.head()

,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,Price,ScreenWidth,ScreenHeight,IPS,CpuBrand,CpuSpeed
0,Apple,Ultrabook,13.3,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,2560,1600,1,Intel,2.3
1,Apple,Ultrabook,13.3,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,1440,900,0,Intel,1.8
2,HP,Notebook,15.6,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,1920,1080,0,Intel,2.5
3,Apple,Ultrabook,15.4,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,2880,1800,1,Intel,2.7
4,Apple,Ultrabook,13.3,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,2560,1600,1,Intel,3.1

In [23]:
df["Memory"].str.split().str[-1].value_counts()

Memory
SSD        641
HDD        576
Storage     74
Hybrid      12
Name: count, dtype: int64

In [24]:
df["Memory"].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
1TB SSD                           14
512GB SSD +  1TB HDD              14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
16GB SSD                           3
512GB SSD +  2TB HDD               3
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
64GB SSD                           1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
512GB SSD +  256GB SSD             1
32GB HDD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [25]:
df["Memory"].str.contains("SSD")

0        True
1       False
2        True
3        True
4        True
        ...
1298     True
1299     True
1300    False
1301    False
1302    False
Name: Memory, Length: 1303, dtype: bool

In [26]:
import re

def get_storage(memory, storage_type):

    pattern = rf"(\d+(?:\.\d+)?)\s*(GB|TB)\s+{storage_type}"

    match = re.search(pattern, memory)

    if match:
        value = float(match.group(1))
        unit = match.group(2)

        if unit == "TB":
            value *= 1024

        return value

    return 0

In [27]:
df["SSD_GB"] = df["Memory"].apply(lambda x: get_storage(x, "SSD"))
df["HDD_GB"] = df["Memory"].apply(lambda x: get_storage(x, "HDD"))
df["Hybrid_GB"] = df["Memory"].apply(lambda x: get_storage(x, "Hybrid"))
df["Flash_GB"] = df["Memory"].apply(lambda x: get_storage(x, "Flash"))

In [28]:
df.head()

,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,Price,ScreenWidth,ScreenHeight,IPS,CpuBrand,CpuSpeed,SSD_GB,HDD_GB,Hybrid_GB,Flash_GB
0,Apple,Ultrabook,13.3,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,2560,1600,1,Intel,2.3,128.0,0.0,0.0,0.0
1,Apple,Ultrabook,13.3,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,1440,900,0,Intel,1.8,0.0,0.0,0.0,128.0
2,HP,Notebook,15.6,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,1920,1080,0,Intel,2.5,256.0,0.0,0.0,0.0
3,Apple,Ultrabook,15.4,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,2880,1800,1,Intel,2.7,512.0,0.0,0.0,0.0
4,Apple,Ultrabook,13.3,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,2560,1600,1,Intel,3.1,256.0,0.0,0.0,0.0

In [29]:
df.drop("Memory", axis=1, inplace=True)

In [30]:
df["GpuBrand"] = df["Gpu"].str.split().str[0]

In [31]:
df["GpuBrand"].value_counts()

GpuBrand
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [32]:
df.drop("Gpu", axis=1, inplace=True)

In [33]:
df.head()

,Company,TypeName,Inches,Ram,OpSys,Weight,Price,ScreenWidth,ScreenHeight,IPS,CpuBrand,CpuSpeed,SSD_GB,HDD_GB,Hybrid_GB,Flash_GB,GpuBrand
0,Apple,Ultrabook,13.3,8,macOS,1.37,71378.6832,2560,1600,1,Intel,2.3,128.0,0.0,0.0,0.0,Intel
1,Apple,Ultrabook,13.3,8,macOS,1.34,47895.5232,1440,900,0,Intel,1.8,0.0,0.0,0.0,128.0,Intel
2,HP,Notebook,15.6,8,No OS,1.86,30636.0000,1920,1080,0,Intel,2.5,256.0,0.0,0.0,0.0,Intel
3,Apple,Ultrabook,15.4,16,macOS,1.83,135195.3360,2880,1800,1,Intel,2.7,512.0,0.0,0.0,0.0,AMD
4,Apple,Ultrabook,13.3,8,macOS,1.37,96095.8080,2560,1600,1,Intel,3.1,256.0,0.0,0.0,0.0,Intel

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
x = df.drop("Price", axis=1)
y = df["Price"]

In [37]:
numerical_cols = [
    "Inches",
    "Ram",
    "Weight",
    "ScreenWidth",
    "ScreenHeight",
    "IPS",
    "CpuSpeed",
    "SSD_GB",
    "HDD_GB",
    "Hybrid_GB",
    "Flash_GB"
]

In [38]:
categorical_cols = [
    "Company",
    "TypeName",
    "OpSys",
    "CpuBrand",
    "GpuBrand"
]

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)

In [42]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [45]:
model.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Inches', 'Ram', 'Weight',
                                                   'ScreenWidth',
                                                   'ScreenHeight', 'IPS',
                                                   'CpuSpeed', 'SSD_GB',
                                                   'HDD_GB', 'Hybrid_GB',
                                                   'Flash_GB']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Company', 'TypeName',
                                                   'OpSys', 'CpuBrand',
                                                   'GpuBrand'])])),
                ('regressor', LinearRegression())])

In [46]:
y_pred = model.predict(x_test)

In [47]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

R2 Score: 0.7821925429593508

In [49]:
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ))
])

rf_model.fit(x_train, y_train)

y_pred_rf = rf_model.predict(x_test)

print("R2:", r2_score(y_test, y_pred_rf))

R2: 0.8239256913384044

In [50]:
from sklearn.ensemble import GradientBoostingRegressor

gb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", GradientBoostingRegressor(random_state=42))
])

gb_model.fit(x_train, y_train)

y_pred_gb = gb_model.predict(x_test)

print("R2:", r2_score(y_test, y_pred_gb))

R2: 0.836126694106595

In [51]:
final_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", GradientBoostingRegressor(random_state=42))
])

In [52]:
final_model.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Inches', 'Ram', 'Weight',
                                                   'ScreenWidth',
                                                   'ScreenHeight', 'IPS',
                                                   'CpuSpeed', 'SSD_GB',
                                                   'HDD_GB', 'Hybrid_GB',
                                                   'Flash_GB']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Company', 'TypeName',
                                                   'OpSys', 'CpuBrand',
                                                   'GpuBrand'])])),
                ('regressor', GradientBoostingRegressor(random_state=42))])

In [55]:
import pickle

with open("laptop_price_model.pkl", "wb") as f:
    pickle.dump(final_model, f)